### ISSUE TITLE
Python 3 version?

### ISSUE THREAD

**Issue by naught101** [PyMVPA/PyMVPA#128]
Is there any work being done on a conversion to python 3? If not, would that work be welcome, or is python 2.x end-of-life for pyMVPA? Are there any prerequisite packages that are not yet available for python 3?

**Comment by hanke** [comment]
And here is the anual "let's do it later".

**Comment by BubbaRich** [comment]
This seems more superficial than what you are talking about.  I built and installed it with Python3, I watched a lot of Python2to3 scroll past, but when I try to import it, I get this error.  Any idea?

Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mvpa2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bubbarich/PyMVPA/PyMVPA/mvpa2/__init__.py", line 52, in <module>
    from mvpa2.base import cfg
  File "/Users/bubbarich/PyMVPA/PyMVPA/mvpa2/base/__init__.py", line 24, in <module>
    from mvpa2.base.config import ConfigManager
  File "/Users/bubbarich/PyMVPA/PyMVPA/mvpa2/base/config.py", line 228
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

**Comment by yarikoptic** [comment]
looks like you are importing original,  not  converted  codebase ( should be  somewhere under  build iirc)

**Comment by bakerhassan** [comment]
Do you guys have an update about this?

**Comment by yarikoptic** [comment]
Unfortunately my attempt in https://github.com/PyMVPA/PyMVPA/pull/525 had stalled... No ETA ATM

**Comment by bakerhassan** [comment]
@yarikoptic Thanks. I'm running Python 3 but no issues so far. But I see there are tests fail in the pull requests that you tagged. In the docs, however, it says it should work. Can you give me a brief update whether it's stable or not on Python 3?

**Comment by yarikoptic** [comment]
Personally - I wouldn't! Some results could come out not right, as some of the failing tests suggest.

**Comment by yarikoptic** [comment]
But thanks for bringing this discussion - shows that there is a demand, so... might find time or help

**Comment by alansill** [comment]
Our HPC center is strongly discouraging users from continuing to use software that requires Python 2, since that version of Python is no longer being maintained and is not receiving security updates. Updating PyMVPA to work in Python 3 is advised.
