### ISSUE TITLE
Failure in test_group_clusterthreshold_simple

### ISSUE THREAD

**Issue by nno** [PyMVPA/PyMVPA#292]
Re recent PR #284 (@hanke, @dinga92): Travis just reported a failure when thresholding: https://travis-ci.org/nno/PyMVPA/jobs/61130449. 

FAIL: mvpa2.tests.test_group_clusterthr.test_group_clusterthreshold_simple
 ----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 622, in newfunc
    return func(*arg, **kw)
  File "/home/travis/build/nno/PyMVPA/mvpa2/tests/test_group_clusterthr.py", line 205, in test_group_clusterthreshold_simple
    assert_array_equal(res.a.clusterstats, shifted_res.a.clusterstats)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 707, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 636, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
 Single scenario lead to failures of unittest test_group_clusterthreshold_simple:
  on
    n_proc=2 :
     
Arrays are not equal
(mismatch 50.0%)
 x: rec.array([(5, 0.0024875621890547263, 0.004975124378109453),
       (1, 0.029850746268656716, 0.029850746268656716)], 
      dtype=[('size', '<i8'), ('prob_raw', '<f8'), ('prob_corrected', '<f8')])
 y: rec.array([(4, 0.0024875621890547263, 0.004975124378109453),
       (1, 0.029850746268656716, 0.029850746268656716)], 
      dtype=[('size', '<i8'), ('prob_raw', '<f8'), ('prob_corrected', '<f8')])

**Comment by hanke** [comment]
Pushed tentative fix. On my machine it didn't fail for 100 iterations.

**Comment by hanke** [comment]
Seems to work again.
