### ISSUE TITLE
Failing tests with assert_objectarray_equal

### ISSUE THREAD

**Issue by nno** [PyMVPA/PyMVPA#301]
Currently OSX 10.5, 10.6, 10.8 [e.g. http://nipy.bic.berkeley.edu/builders/pymvpa-py2.7-osx-10.6/builds/276/steps/shell_5/logs/stdio] may give errors in assert_objectarray_equal, which seems to be caused by rounding errors.

@yarikoptic @hanke would it be good to add another function, assert_objectarray_almost_equal, to deal with such situations?

FAIL: mvpa2.tests.test_fxmapper.test_fx_native_calls
 ----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/buildslave/osx-10.6/pymvpa-py2_7-osx-10_6/build/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/buildslave/osx-10.6/pymvpa-py2_7-osx-10_6/build/venv/lib/python2.7/site-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "/Users/buildslave/osx-10.6/pymvpa-py2_7-osx-10_6/build/venv/lib/python2.7/site-packages/mvpa2/tests/test_fxmapper.py", line 220, in test_fx_native_calls
    assert_objectarray_equal(dsm1.samples, dsm2.samples)
  File "/Users/buildslave/osx-10.6/pymvpa-py2_7-osx-10_6/build/venv/lib/python2.7/site-packages/mvpa2/testing/tools.py", line 326, in assert_objectarray_equal
    assert_array_equal(x, y)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 739, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
 Single scenario lead to failures of unittest test_fx_native_calls:
  on
    f=average :
     
Arrays are not equal

(mismatch 66.6666666667%)
 x: array([[ 0.343741, -0.016952,  0.013869, -0.004369, -0.016687,  0.312285]])
 y: array([[ 0.343741, -0.016952,  0.013869, -0.004369, -0.016687,  0.312285]])
    f=mean :

**Comment by hanke** [comment]
@nno Am I missing something: why objectarray? Looks like numerical array? And what would an almost-equal object look like?

**Comment by nno** [comment]
@hanke good point, actually we can just do the comparison directly on numerical arrays. I'll send a PR shortly.

**Comment by nno** [comment]
@yarikoptic git-blame lists you as the author of the original code that would be changed by #303.
Are @hanke and I missing something, or can we just do direct numerical comparison here?

**Comment by nno** [comment]
Actually travis is now failing on older numpy/scipy [https://travis-ci.org/PyMVPA/PyMVPA/jobs/61313077] so it's not ready for merging yet.

**Comment by hanke** [comment]
OSX os good again:

http://nipy.bic.berkeley.edu/builders/pymvpa-py2.7-osx-10.6/builds/291

Closing.
