### ISSUE TITLE
_create_small_mat_nbrhood_dict errors while test_cosmo_queryengine

### ISSUE THREAD

**Issue by yarikoptic** [PyMVPA/PyMVPA#305]
@nno -- are those "interesting" or something dealt with?
http://nipy.bic.berkeley.edu/builders/pymvpa-py2.7-win32/builds/111/steps/shell_5/logs/stdio

```
======================================================================
ERROR: mvpa2.tests.test_cosmo.test_cosmo_queryengine
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\mvpa2\testing\tools.py", line 165, in newfunc
    func(*(arg + (filename,)), **kw)
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\mvpa2\tests\test_cosmo.py", line 182, in test_cosmo_queryengine
    nbrhood_mat = _create_small_mat_nbrhood_dict()
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\mvpa2\tests\test_cosmo.py", line 92, in _create_small_mat_nbrhood_dict
    arr([[1, 2, 3]]), arr([[2, 2]])]], dtype='O')
  File "C:\Python27\lib\site-packages\numpy\core\numeric.py", line 462, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (2) into shape (1)

======================================================================
ERROR: mvpa2.tests.test_cosmo.test_cosmo_searchlight
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\mvpa2\tests\test_cosmo.py", line 200, in test_cosmo_searchlight
    _create_small_mat_nbrhood_dict())
  File "c:\buildslaves\win7-32-mini\pymvpa-py2_7-win32\build\venv\lib\site-packages\mvpa2\tests\test_cosmo.py", line 92, in _create_small_mat_nbrhood_dict
    arr([[1, 2, 3]]), arr([[2, 2]])]], dtype='O')
  File "C:\Python27\lib\site-packages\numpy\core\numeric.py", line 462, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (2) into shape (1)
...
```

**Comment by nno** [comment]
@yarikoptic the broadcasting issue should be fixed by PR #299, addressing #229 as well.

**Comment by nno** [comment]
@yarikoptic as PR #299 has been merged, are you ok to close this issue?

**Comment by yarikoptic** [comment]
and http://nipy.bic.berkeley.edu/builders/pymvpa-py2.7-win32/builds/120/steps/shell_5/logs/stdio is quiet about them -- so good -- closing
