### ISSUE TITLE
bunch of tests started to fail with RuntimeError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by yarikoptic** [PyMVPA/PyMVPA#344]
NB WTF details are below
```
======================================================================
ERROR: mvpa2.tests.test_viz.test_hist
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/pymvpa/pymvpa/mvpa2/tests/test_viz.py", line 35, in test_hist
    noticks=None, xlim=(-.5, .5), normed=True)
  File "/home/yoh/proj/pymvpa/pymvpa/mvpa2/viz/__init__.py", line 114, in hist
    ax = pl.subplot(nrows, ncols, fig)
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 922, in subplot
    a = fig.add_subplot(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 958, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_subplots.py", line 78, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 424, in __init__
    self._init_axis()
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 481, in _init_axis
    self.xaxis = maxis.XAxis(self)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 666, in __init__
    self.cla()
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 754, in cla
    self.reset_ticks()
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 767, in reset_ticks
    self.majorTicks.extend([self._get_tick(major=True)])
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 1662, in _get_tick
    return XTick(self.axes, 0, '', major=major, **tick_kw)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 148, in __init__
    self.tick1line = self._get_tick1line()
  File "/usr/lib/python2.7/dist-packages/matplotlib/axis.py", line 398, in _get_tick1line
    zorder=self._zorder,
  File "/usr/lib/python2.7/dist-packages/matplotlib/lines.py", line 326, in __init__
    self._marker = MarkerStyle()
  File "/usr/lib/python2.7/dist-packages/matplotlib/markers.py", line 169, in __init__
    self.set_marker(marker)
  File "/usr/lib/python2.7/dist-packages/matplotlib/markers.py", line 250, in set_marker
    self._recache()
  File "/usr/lib/python2.7/dist-packages/matplotlib/markers.py", line 183, in _recache
    self._path = Path(np.empty((0, 2)))
  File "/usr/lib/python2.7/dist-packages/matplotlib/path.py", line 157, in __init__
    self._update_values()
  File "/usr/lib/python2.7/dist-packages/matplotlib/path.py", line 201, in _update_values
    rcParams['path.simplify'] and
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 882, in __getitem__
    return dict.__getitem__(self, key)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

```
======================================================================
ERROR: test_surface_outside_volume_voxel_selection (mvpa2.tests.test_surfing_voxelselection.SurfVoxelSelectionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/proj/pymvpa/pymvpa/mvpa2/testing/tools.py", line 180, in newfunc
    func(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/pymvpa/pymvpa/mvpa2/tests/test_surfing_voxelselection.py", line 444, in test_surface_outside_volume_voxel_selection
    sel = selector()
  File "/home/yoh/proj/pymvpa/pymvpa/mvpa2/tests/test_surfing_voxelselection.py", line 439, in <lambda>
    outside_node_margin=outside_node_margin)
  File "/home/yoh/proj/pymvpa/pymvpa/mvpa2/misc/surfing/surf_voxel_selection.py", line 598, in voxel_selection
    for i, result in enumerate(results):
  File "/usr/lib/pymodules/python2.7/pprocess.py", line 764, in next
    self.store()
  File "/usr/lib/pymodules/python2.7/pprocess.py", line 400, in store
    self.store_data(channel)
  File "/usr/lib/pymodules/python2.7/pprocess.py", line 747, in store_data
    data = channel.receive()
  File "/usr/lib/pymodules/python2.7/pprocess.py", line 135, in receive
    obj = self._receive()
  File "/usr/lib/pymodules/python2.7/pprocess.py", line 121, in _receive
    raise obj
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

```
Current date:   2015-07-20 10:18
PyMVPA:
 Version:       2.4.0
 Hash:          $Format:%H$
 Path:          mvpa2/__init__.pyc
 Version control (GIT):
  Status:
   On branch master
   Your branch is behind 'origin/master' by 33 commits, and can be fast-forwarded.
     (use "git pull" to update your local branch)
   Changes not staged for commit:
     (use "git add <file>..." to update what will be committed)
     (use "git checkout -- <file>..." to discard changes in working directory)
   
   	modified:   mvpa2/base/config.py
   	modified:   mvpa2/base/externals.py
   
   Untracked files:
     (use "git add <file>..." to include in what will be committed)
   
   	.duecredit.p
   	.idea/
   	.ipynb_checkpoints/
   	.noseids
   	1.py
   	123.x11
   	3rd/bibstuff/
   	3rd/pybetaseries/
   	INSTALL.1/
   	Makefile.troubleexample
   	TODO.nick-maybe.txt
   	doc/broken.links
   	doc/examples/clfs_examples.py_TROUBLESHOOT
   	doc/misc/references_ascii.bib
   	doc/pics/pymvpa_logo_pie.svg
   	doc/source/tutorial_classifiers-script.py
   	doc/source/tutorial_classifiers.html
   	doc/source/tutorial_eventrelated-script.py
   	getattr-error.txt
   	hyper-orig.log
   	hyper-patched.log
   	mvpa2/algorithms/hyperalignment.py_randomlevel2
   	mvpa2/data/tutorial_data_20mm/
   	mvpa2/data/tutorial_data_masked/
   	mvpa2/measures/glm_features.py.copy
   	mvpa2/measures/test_glm_features.py.copy
   	mvpa2/tests/badexternals2/
   	mvpa2/tests/test_datameasure.py.andytoyingaround
   	mvpa2/tests/test_hyperalignment.py.orig
   	mvpa2/tests/test_testing.py_aside
   	protocol
   	py3-failures.txt
   	pymvpa2.cfg.causechaos
   	pymvpa2.egg-info/
   	testmanual-2.log
   	testmanual.log
   	tmpvoxsel__tmp__1929569183_1.h5py
   	tmpvoxsel__tmp__1942361503_2.h5py
   	tmpvoxsel__tmp__1963967391_3.h5py
   	tmpvoxsel__tmp__1987003807_4.h5py
   	tmpvoxsel__tmp__2502704541_2.h5py
   	tmpvoxsel__tmp__2515178281_1.h5py
   	tmpvoxsel__tmp__2534325545_2.h5py
   	tmpvoxsel__tmp__2544871721_3.h5py
   	tmpvoxsel__tmp__2551907741_4.h5py
   	tmpvoxsel__tmp__2554287005_1.h5py
   	tmpvoxsel__tmp__2581735209_4.h5py
   	tmpvoxsel__tmp__2597867933_3.h5py
   	tmpvoxsel__tmp__2735656233_1.h5py
   	tmpvoxsel__tmp__2741353257_2.h5py
   	tmpvoxsel__tmp__2763733409_1.h5py
   	tmpvoxsel__tmp__2769647521_2.h5py
   	tmpvoxsel__tmp__2770164009_3.h5py
   	tmpvoxsel__tmp__2786190633_4.h5py
   	tmpvoxsel__tmp__2792510762_1.h5py
   	tmpvoxsel__tmp__2804291882_2.h5py
   	tmpvoxsel__tmp__2822519594_3.h5py
   	tmpvoxsel__tmp__2835492652_1.h5py
   	tmpvoxsel__tmp__2837072289_4.h5py
   	tmpvoxsel__tmp__2844062109_1.h5py
   	tmpvoxsel__tmp__2849389354_4.h5py
   	tmpvoxsel__tmp__2874820509_2.h5py
   	tmpvoxsel__tmp__2902009757_3.h5py
   	tmpvoxsel__tmp__2909256492_2.h5py
   	tmpvoxsel__tmp__2943648553_1.h5py
   	tmpvoxsel__tmp__2960961833_2.h5py
   	tmpvoxsel__tmp__2967669149_4.h5py
   	tmpvoxsel__tmp__2979902252_4.h5py
   	tmpvoxsel__tmp__2992121641_3.h5py
   	tmpvoxsel__tmp__3003666729_4.h5py
   	tmpvoxsel__tmp__3083218849_3.h5py
   	tmpvoxsel__tmp__3109279532_3.h5py
   	tmpvoxsel__tmp__3147001245_1.h5py
   	tmpvoxsel__tmp__3163810601_1.h5py
   	tmpvoxsel__tmp__3165306273_1.h5py
   	tmpvoxsel__tmp__3175690537_2.h5py
   	tmpvoxsel__tmp__3183297949_2.h5py
   	tmpvoxsel__tmp__3200490913_2.h5py
   	tmpvoxsel__tmp__3207780649_3.h5py
   	tmpvoxsel__tmp__3209935261_3.h5py
   	tmpvoxsel__tmp__3212713257_4.h5py
   	tmpvoxsel__tmp__3272760225_3.h5py
   	tmpvoxsel__tmp__3273975709_4.h5py
   	tmpvoxsel__tmp__3309666721_4.h5py
   	tmpvoxsel__tmp__3367740204_1.h5py
   	tmpvoxsel__tmp__3404400541_1.h5py
   	tmpvoxsel__tmp__3450446124_2.h5py
   	tmpvoxsel__tmp__3471407916_3.h5py
   	tmpvoxsel__tmp__3479912861_2.h5py
   	tmpvoxsel__tmp__3490119581_4.h5py
   	tmpvoxsel__tmp__3493552428_4.h5py
   	tmpvoxsel__tmp__3552957341_3.h5py
   	venv-nibabel1.0/
   	venv-nibabel1.2.2/
   	venv-test/
   	wtf-here.log
   	wtf-sandbox.log
   
   no changes added to commit (use "git add" and/or "git commit -a")
  Reference:
   787522cdca3880c85353751e9e6c538caa2f4bc6 HEAD
  Difference from last release 2.4.0:
    55 files changed, 1574 insertions(+), 591 deletions(-)
SYSTEM:
 OS:            posix Linux 3.17-1-amd64 #1 SMP Debian 3.17-1~exp1 (2014-10-14)
 Distribution:  debian/stretch/sid
EXTERNALS:
 Present:       atlas_fsl, cPickle, ctypes, elasticnet, good scipy.stats.rv_continuous._reduce_func(floc,fscale), good scipy.stats.rv_discrete.ppf, griddata, gzip, h5py, hdf5, ipython, joblib, liblapack.so, libsvm, libsvm verbosity control, lxml, mass, matplotlib, mdp, mdp ge 2.4, mock, nibabel, nipy, nose, numpy, numpy_correct_unique, numpydoc, openopt, pprocess, pylab, pylab plottable, pywt, pywt wp reconstruct, reportlab, rpy2, scipy, sg ge 0.6.4, sg ge 0.6.5, sg_fixedcachesize, shogun.mpd, shogun.svmocas, skl, statsmodels, weave
 Absent:        atlas_pymvpa, cran-energy, glmnet, good scipy.stats.rdist, hcluster, lars, nipy.neurospin, pywt wp reconstruct fixed, running ipython env, shogun, shogun.krr, shogun.lightsvm, shogun.svrlight
 Versions of critical externals:
  ctypes      : 1.1.0
  h5py        : 2.5.0
  hdf5        : 1.8.13
  ipython     : 2.3.0
  lxml        : 3.4.2
  matplotlib  : 1.4.2
  mdp         : 3.3
  mock        : 1.0.1
  nibabel     : 2.0.1
  nipy        : 0.4.0.dev
  numpy       : 1.8.2
  openopt     : 0.38
  pprocess    : 0.5
  reportlab   : 3.2.0
  rpy2        : 2.6.0
  scipy       : 0.14.1
  shogun      : 3.2.0
  shogun:full : 3.2.0_2014-2-17_18:46
  shogun:rev  : 197120
  skl         : 0.16.1
 Matplotlib backend: TkAgg
RUNTIME:
 PyMVPA Environment Variables:
  PYTHONPATH          : ":/usr/lib/python2.7/lib-old:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/lib-dynload:/usr/lib/ITK-4.7/Python:/home/yoh/.local/lib/python2.7/site-packages:/home/yoh/proj/pymvpa/pymvpa:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/dist-packages/gtk-2.0:/home/yoh/proj/duecredit:/usr/lib:/usr/lib/python2.7/dist-packages:/usr/lib/pymodules/python2.7:/usr/lib/python2.7/dist-packages/IPython/extensions:/usr/lib/python2.7:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/wx-3.0-gtk2:/home/yoh/proj/datalad/datalad"
 PyMVPA Runtime Configuration:
  [general]
  verbose = 1
  
  [externals]
  have glmnet = no
  have lars = no
  have shogun = no
  have running ipython env = no
  have numpy = yes
  have scipy = yes
  have matplotlib = yes
  have lxml = yes
  have nibabel = yes
  have atlas_fsl = yes
  have atlas_pymvpa = no
  have cpickle = yes
  have rpy2 = yes
  have cran-energy = no
  have ctypes = yes
  have elasticnet = yes
  have good scipy.stats.rdist = no
  have good scipy.stats.rv_continuous._reduce_func(floc,fscale) = yes
  have good scipy.stats.rv_discrete.ppf = yes
  have griddata = yes
  have gzip = yes
  have h5py = yes
  have hcluster = no
  have hdf5 = yes
  have ipython = yes
  have joblib = yes
  have liblapack.so = yes
  have libsvm = yes
  have libsvm verbosity control = yes
  have mass = yes
  have mdp = yes
  have mdp ge 2.4 = yes
  have mock = yes
  have nipy = yes
  have nipy.neurospin = no
  have nose = yes
  have numpy_correct_unique = yes
  have numpydoc = yes
  have openopt = yes
  have pprocess = yes
  have pylab = yes
  have pylab plottable = yes
  have pywt = yes
  have pywt wp reconstruct = yes
  have pywt wp reconstruct fixed = no
  have reportlab = yes
  have sg ge 0.6.4 = yes
  have sg ge 0.6.5 = yes
  have sg_fixedcachesize = yes
  have shogun.krr = no
  have shogun.lightsvm = no
  have shogun.mpd = yes
  have shogun.svmocas = yes
  have shogun.svrlight = no
  have skl = yes
  have statsmodels = yes
  have weave = yes
```

**Comment by nno** [comment]
Strange, I'm unable to reproduce on neurodebian or OSX. ``nosetests test_surfing_voxelselection.py`` returns with no errors.

wtf output:

    Current date:   2015-07-23 13:04
    PyMVPA:
     Version:       2.4.0
     Hash:          $Format:%H$
     Path:          mvpa2/__init__.pyc
     Version control (GIT):
      Status:
       # On branch master
       nothing to commit (working directory clean)
      Reference:
       ec585405e57ae2a4d447c4c47183f4fc9913c534 HEAD
       ec585405e57ae2a4d447c4c47183f4fc9913c534 refs/remotes/origin/HEAD
      Difference from last release 2.4.0:
        79 files changed, 2370 insertions(+), 869 deletions(-)
    SYSTEM:
     OS:            posix Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1
     Distribution:  debian/7.8
    EXTERNALS:
     Present:       cPickle, ctypes, good scipy.stats.rdist, good scipy.stats.rv_discrete.ppf, griddata, gzip, h5py, hdf5, ipython, joblib, liblapack.so, matplotlib, mdp, mdp ge 2.4, nibabel, nose, numpy, numpy_correct_unique, pprocess, pylab, pylab plottable, running ipython env, scipy, skl, weave
     Absent:        atlas_fsl, atlas_pymvpa, cran-energy, elasticnet, glmnet, good scipy.stats.rv_continuous._reduce_func(floc,fscale), hcluster, lars, libsvm, libsvm verbosity control, lxml, mass, mock, nipy, nipy.neurospin, numpydoc, openopt, pywt, pywt wp reconstruct, pywt wp reconstruct fixed, reportlab, rpy2, sg ge 0.6.4, sg ge 0.6.5, sg_fixedcachesize, shogun, shogun.krr, shogun.lightsvm, shogun.mpd, shogun.svmocas, shogun.svrlight, statsmodels
     Versions of critical externals:
      ctypes      : 1.1.0
      h5py        : 2.5.0
      hdf5        : 1.8.8
      ipython     : 0.13.1
      matplotlib  : 1.1.1rc2
      mdp         : 3.4
      nibabel     : 1.3.0
      numpy       : 1.6.2
      pprocess    : 0.5
      scipy       : 0.10.1
      skl         : 0.16.1
     Matplotlib backend: TkAgg
    RUNTIME:
     PyMVPA Environment Variables:
      PYTHONPATH          : ":/usr/lib/python2.7/lib-old:/usr/local/lib/python2.7/dist-packages:/home/brain/tmp/PyMVPA:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/plat-linux2:/usr/bin:/media/sf_mac/git/PyMVPA:/home/brain/.python27_compiled:/usr/lib/python2.7/dist-packages:/usr/lib/pymodules/python2.7:/usr/lib/python2.7:/usr/lib/python2.7/dist-packages/IPython/extensions:/usr/local/lib/python2.7/dist-packages/Cython-0.22-py2.7-linux-x86_64.egg:/usr/lib/python2.7/dist-packages/gtk-2.0:/usr/lib/python2.7/dist-packages/PIL"
     PyMVPA Runtime Configuration:
      [general]
      verbose = 1
      
      [externals]
      have running ipython env = yes
      have ipython = yes
      have numpy = yes
      have scipy = yes
      have matplotlib = yes
      have h5py = yes
      have reportlab = no
      have weave = yes
      have good scipy.stats.rdist = yes
      have good scipy.stats.rv_discrete.ppf = yes
      have good scipy.stats.rv_continuous._reduce_func(floc,fscale) = no
      have pylab = yes
      have lars = no
      have elasticnet = no
      have glmnet = no
      have skl = yes
      have ctypes = yes
      have libsvm = no
      have shogun = no
      have openopt = no
      have nibabel = yes
      have mdp = yes
      have mdp ge 2.4 = yes
      have nipy = no
      have statsmodels = no
      have pywt = no
      have cpickle = yes
      have gzip = yes
      have cran-energy = no
      have griddata = yes
      have nipy.neurospin = no
      have lxml = no
      have atlas_fsl = no
      have atlas_pymvpa = no
      have hcluster = no
      have hdf5 = yes
      have joblib = yes
      have liblapack.so = yes
      have libsvm verbosity control = no
      have mass = no
      have mock = no
      have nose = yes
      have numpy_correct_unique = yes
      have numpydoc = no
      have pprocess = yes
      have pylab plottable = yes
      have pywt wp reconstruct = no
      have pywt wp reconstruct fixed = no
      have rpy2 = no
      have sg ge 0.6.4 = no
      have sg ge 0.6.5 = no
      have sg_fixedcachesize = no
      have shogun.krr = no
      have shogun.lightsvm = no
      have shogun.mpd = no
      have shogun.svmocas = no
      have shogun.svrlight = no
     Process Information:
      Name:	ipython
      State:	R (running)
      Tgid:	2559
      Pid:	2559
      PPid:	31117
      TracerPid:	0
      Uid:	1000	1000	1000	1000
      Gid:	1000	1000	1000	1000
      FDSize:	256
      Groups:	24 25 27 29 30 44 46 103 1000 
      VmPeak:	  572944 kB
      VmSize:	  570840 kB
      VmLck:	       0 kB
      VmPin:	       0 kB
      VmHWM:	   95380 kB
      VmRSS:	   93312 kB
      VmData:	   97532 kB
      VmStk:	     136 kB
      VmExe:	    2396 kB
      VmLib:	   55540 kB
      VmPTE:	    1068 kB
      VmSwap:	       0 kB
      Threads:	3
      SigQ:	1/8104
      SigPnd:	0000000000000000
      ShdPnd:	0000000000000000
      SigBlk:	0000000000000000
      SigIgn:	0000000001001000
      SigCgt:	0000000180000002
      CapInh:	0000000000000000
      CapPrm:	0000000000000000
      CapEff:	0000000000000000
      CapBnd:	ffffffffffffffff
      Cpus_allowed:	1
      Cpus_allowed_list:	0
      Mems_allowed:	00000000,00000001
      Mems_allowed_list:	0
      voluntary_ctxt_switches:	3624
      nonvoluntary_ctxt_switches:	481

**Comment by nno** [comment]
@yarikoptic is this still an issue?

**Comment by yarikoptic** [comment]
Didn't check recently. Will do later
