### ISSUE TITLE
data type change detected on 32bit in test_surface_dset_niml_io_with_unicode

### ISSUE THREAD

**Issue by yarikoptic** [PyMVPA/PyMVPA#375]
```
======================================================================
FAIL: test_surface_dset_niml_io_with_unicode (mvpa2.tests.test_surfing_afni.SurfTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pymvpa2-2.4.0.1/debian/tmp/usr/lib/python2.7/dist-packages/mvpa2/testing/tools.py", line 255, in newfunc
    func(*(arg + (filename,)), **kw)
  File "/build/pymvpa2-2.4.0.1/debian/tmp/usr/lib/python2.7/dist-packages/mvpa2/tests/test_surfing_afni.py", line 189, in test_surface_dset_niml_io_with_unicode
    assert_datasets_equal(ds, ds2)
  File "/build/pymvpa2-2.4.0.1/debian/tmp/usr/lib/python2.7/dist-packages/mvpa2/testing/tools.py", line 147, in assert_datasets_equal
    ignore_fa=ignore_fa, decimal=None)
  File "/build/pymvpa2-2.4.0.1/debian/tmp/usr/lib/python2.7/dist-packages/mvpa2/testing/tools.py", line 133, in assert_datasets_almost_equal
    assert_equal(x.samples.dtype, y.samples.dtype)
AssertionError: dtype('int32') != dtype('int64')
```

if you need such 32 bit env -- let me know, I will either give instructions or access to such.

Cheers

**Comment by yarikoptic** [comment]
It was fixed in #377
