### ISSUE TITLE
numpy 1.10 compatibility

### ISSUE THREAD

**Issue by ignatenkobrain** [PyMVPA/PyMVPA#381]
```python
======================================================================
ERROR: Test all classifiers for conformant behavior
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/PyMVPA-upstream-2.4.0/mvpa2/tests/test_clf.py", line 916, in test_generic_tests
    clf.train(traindata)
  File "/builddir/build/BUILD/PyMVPA-upstream-2.4.0/mvpa2/base/learner.py", line 132, in train
    result = self._train(ds)
  File "/builddir/build/BUILD/PyMVPA-upstream-2.4.0/mvpa2/clfs/meta.py", line 1371, in _train
    self.__mapper.train(dataset)
  File "/builddir/build/BUILD/PyMVPA-upstream-2.4.0/mvpa2/base/learner.py", line 132, in train
    result = self._train(ds)
  File "/builddir/build/BUILD/PyMVPA-upstream-2.4.0/mvpa2/featsel/base.py", line 320, in _train
    selected_ids = self._get_selected_ids(dataset)
  File "/builddir/build/BUILD/PyMVPA-upstream-2.4.0/mvpa2/featsel/base.py", line 296, in _get_selected_ids
    sensitivity = self.__sensitivity_analyzer(dataset)
  File "/builddir/build/BUILD/PyMVPA-upstream-2.4.0/mvpa2/base/learner.py", line 259, in __call__
    return super(Learner, self).__call__(ds)
  File "/builddir/build/BUILD/PyMVPA-upstream-2.4.0/mvpa2/base/node.py", line 121, in __call__
    result = self._call(ds)
  File "/builddir/build/BUILD/PyMVPA-upstream-2.4.0/mvpa2/measures/anova.py", line 88, in _call
    sostot /= bign
TypeError: ufunc 'divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''
```

**Comment by ignatenkobrain** [comment]
The same was done in nipy projects, e.g. https://github.com/nipy/dipy/pull/731/
