### ISSUE TITLE
searchlight hyperalignment tests fails sometimes

### ISSUE THREAD

**Issue by nno** [PyMVPA/PyMVPA#455]
Running travis for PR #454, the following test sometimes fails [1]:
```
======================================================================
FAIL: test_searchlight_hyperalignment (mvpa2.tests.test_searchlight_hyperalignment.SearchlightHyperalignmentTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/nno/PyMVPA/mvpa2/testing/tools.py", line 331, in newfunc
    return func(*arg, **kwargs)
  File "/home/travis/build/nno/PyMVPA/mvpa2/tests/test_searchlight_hyperalignment.py", line 245, in test_searchlight_hyperalignment
    assert(np.sum(max_weight == diag_weight) / float(len(diag_weight)) > 0.98)
AssertionError
```
Ping @swaroopgj 
[1] https://travis-ci.org/nno/PyMVPA/jobs/122044397

**Comment by swaroopgj** [comment]
@nno Thanks Nick. It's an issue with the test being stringent. Will send a PR soon.

**Comment by nno** [comment]
Thanks @swaroopgj, looking forward to the PR (but no rush) :-)

**Comment by yarikoptic** [comment]
Was fixed by #456

**Comment by nno** [comment]
It fails occasionally with
```
assert(np.sum(max_weight == diag_weight) / float(len(diag_weight)) > 0.90)
```
can we use a value lower than 0.90 @swaroopgj?

See: https://travis-ci.org/PyMVPA/PyMVPA/jobs/131643694

**Comment by swaroopgj** [comment]
Thanks Nick. Relaxed the test values for a few tests. Hopefully, this will make them pass for almost all cases.
