### ISSUE TITLE
Error in pymvpa2-prep-afni-surf when generating QA images

### ISSUE THREAD

**Issue by dillonplunkett** [PyMVPA/PyMVPA#574]
Hi,

Using `pymvpa2-prep-afni-surf` for the first time, I'm getting a matplotlib error (below) during the last part of the align step when QA images are generated. If I bypass the QA images (i.e., by commenting out those lines), the same issue arises in the call to `_make_slice_plot` within `run_makesurfmasks`.

I haven't been able to determine why yet. (The alignment itself looks good. The `--anatvol` dtype is float32, as was the image input to `recon-all`. If I bypass both calls to `_make_slice_plot`, the rest of the script runs without error.)

I'm using PyMVPA 2.6.4, matplotlib 2.0.0. 

> Traceback (most recent call last):
  File "/users/dillonplunkett/.conda/envs/default/bin/pymvpa2-prep-afni-surf", line 25, in <module>
    run_prep_afni_surf(vars(d))
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/mvpa2/support/afni/lib_prep_afni_surf.py", line 1404, in run_prep_afni_surf
    run_all(config, environment)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/mvpa2/support/afni/lib_prep_afni_surf.py", line 1260, in run_all
    step2func[step](config, env)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/mvpa2/support/afni/lib_prep_afni_surf.py", line 846, in run_alignment
    _make_slice_plot(fn1, fn2, fnout)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/mvpa2/support/afni/lib_prep_afni_surf.py", line 929, in _make_slice_plot
    output_fn=fnout)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/mvpa2/support/afni/lib_plot_slices.py", line 420, in make_plot
    plt.draw()
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/matplotlib/pyplot.py", line 691, in draw
    get_current_fig_manager().canvas.draw_idle()
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2032, in draw_idle
    self.draw(*args, **kwargs)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/matplotlib/figure.py", line 1143, in draw
    renderer, self, dsu, self.suppressComposite)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2409, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/matplotlib/image.py", line 495, in draw
    renderer, renderer.get_image_magnification())
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/matplotlib/image.py", line 719, in make_image
    unsampled=unsampled)
  File "/users/dillonplunkett/.conda/envs/default/lib/python2.7/site-packages/matplotlib/image.py", line 411, in _make_image
    self.get_filternorm() or 0.0, self.get_filterrad() or 0.0)
ValueError: 3-dimensional arrays must be of dtype unsigned byte, unsigned short, float32 or float64

**Comment by nno** [comment]
Thanks for the report.
Unfortunately it's a bit difficult to track down where things go wrong.
One idea: in ``mvpa2/support/afni/lib_plot_slices.py``, the ``reduce_size`` function casts some arrays to float16. What happens if you change line 46 into
```
return np.asarray(a, dtype=np.float32)
```
?

**Comment by dillonplunkett** [comment]
That doesn't do it, but making the same change here https://github.com/PyMVPA/PyMVPA/blob/709bdf70aa28d358e5adcbae7626e5851394a69f/mvpa2/support/afni/lib_plot_slices.py#L272 in the `blend` function—such that the blended underlays and overlays to be plotted are float32 arrays—works.

(Similarly, it also works to convert each blended slice to float32 as it is passed to `imshow` on line 410.) https://github.com/PyMVPA/PyMVPA/blob/709bdf70aa28d358e5adcbae7626e5851394a69f/mvpa2/support/afni/lib_plot_slices.py#L410

I'd be happy to put together a simple pull request depending on how it would be best to handle it.

**Comment by nno** [comment]
@dillonplunkett thanks for the offer of putting a pull request, I would appreciate that. Cheers!
