### ISSUE TITLE
Tutorial issue

### ISSUE THREAD

**Issue by don-tpanic** [PyMVPA/PyMVPA#592]
Traceback (most recent call last):
  File "pymvpa_tutorial.py", line 60, in <module>
    ds = fmri_dataset(bold_fname)
  File "/Library/Python/2.7/site-packages/mvpa2/datasets/mri.py", line 254, in fmri_dataset
    imgdata, imghdr, img = _load_anyimg(samples, ensure=True, enforce_dim=4)
  File "/Library/Python/2.7/site-packages/mvpa2/datasets/mri.py", line 396, in _load_anyimg
    data = _img2data(src)
  File "/Library/Python/2.7/site-packages/mvpa2/datasets/mri.py", line 72, in _img2data
    img = nibabel.load(src)
  File "/Library/Python/2.7/site-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
nibabel.py3k.FileNotFoundError: No such file or no access: './haxby2001/sub001/BOLD/task001_run001/bold.nii.gz'

**Comment by justinshenk** [comment]
Did you specify the tutorial path with `./pymvpa2-tutorial --tutorial-data-path=[path_to_tutorial]`?

**Comment by yarikoptic** [comment]
indeed path to the tutorial should be specified if not found in a canonical location (sorry - ATM neurodebian specific, `/usr/share/data/pymvpa2-tutorial` as installed in python-mvpa2-tutorialdata pkg), and then symlinked (or copied) under `~/pymvpa2_tutorial/data`.  Things could be improved I guess. But thanks to @justinshenk I would say the issue is resolved, please reopen if it is not
