### ISSUE TITLE
libsvm bindings broke on buster 

### ISSUE THREAD

**Issue by yarikoptic** [PyMVPA/PyMVPA#621]
tried with installed python-mvpa2 pkg and then in virtualenv with current master

```
Traceback (most recent call last):
  File "./r01_do_clf.py", line 193, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./r01_do_clf.py", line 162, in main
    from mvpa2.clfs.libsvmc import svm as libsvm
  File "/home/amanelis/proj/PyMVPA/mvpa2/clfs/libsvmc/svm.py", line 21, in <module>
    from mvpa2.clfs.base import accepts_dataset_as_samples, \
  File "/home/amanelis/proj/PyMVPA/mvpa2/clfs/base.py", line 20, in <module>
    from mvpa2.measures.base import Measure
  File "/home/amanelis/proj/PyMVPA/mvpa2/measures/base.py", line 30, in <module>
    from mvpa2.misc.errorfx import mean_mismatch_error
  File "/home/amanelis/proj/PyMVPA/mvpa2/misc/errorfx.py", line 153, in <module>
    from scipy.stats import pearsonr
  File "/usr/lib/python2.7/dist-packages/scipy/stats/__init__.py", line 345, in <module>
    from .stats import *
  File "/usr/lib/python2.7/dist-packages/scipy/stats/stats.py", line 169, in <module>
    import scipy.special as special
  File "/usr/lib/python2.7/dist-packages/scipy/special/__init__.py", line 640, in <module>
    from ._ufuncs import *
  File "__init__.pxd", line 918, in init scipy.special._ufuncs
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

**Comment by yarikoptic** [comment]
somthing is funny with scipy installation on buster
```
amanelis@beast:/tmp$ python -c 'import scipy.stats'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/scipy/stats/__init__.py", line 345, in <module>
    from .stats import *
  File "/usr/lib/python2.7/dist-packages/scipy/stats/stats.py", line 169, in <module>
    import scipy.special as special
  File "/usr/lib/python2.7/dist-packages/scipy/special/__init__.py", line 640, in <module>
    from ._ufuncs import *
  File "__init__.pxd", line 918, in init scipy.special._ufuncs
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```
